#!/usr/bin/env node
/**
 * Tailscale Devbox — one-command fleet setup for your tailnet.
 * Generates config.yaml, fleet/registry.yaml, and SSH config snippet.
 */
import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const args = process.argv.slice(2);
const nonInteractive = args.includes('--non-interactive') || args.includes('-y');
const installSkill = args.includes('--install-skill');

function getArg(name, fallback = '') {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] ? args[i + 1] : fallback;
}

async function prompt(rl, label, fallback = '') {
  const hint = fallback ? ` [${fallback}]` : '';
  const answer = (await rl.question(`${label}${hint}: `)).trim();
  return answer || fallback;
}

async function loadExample() {
  const path = join(ROOT, 'config.example.yaml');
  const raw = await readFile(path, 'utf8');
  const config = {};
  for (const line of raw.split('\n')) {
    const m = line.match(/^([a-z_]+):\s*(.*)$/);
    if (m) config[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
  return config;
}

function renderRegistry(config) {
  const nodes = [
    { tier: 'primary', host: config.primary_host, user: config.ssh_user, port: config.ssh_port },
  ];
  if (config.backup_host) {
    nodes.push({ tier: 'backup', host: config.backup_host, user: config.ssh_user, port: config.ssh_port });
  }
  if (config.extra_hosts) {
    for (const h of config.extra_hosts.split(',').map((s) => s.trim()).filter(Boolean)) {
      nodes.push({ tier: 'extra', host: h, user: config.ssh_user, port: config.ssh_port });
    }
  }

  let md = `# Devbox Fleet Registry\n\n> Generated by \`npm run init\`. Edit manually after bootstrap.\n\n`;
  md += `| Tier | Host | SSH user | Port | MagicDNS |\n|------|------|----------|------|----------|\n`;
  for (const n of nodes) {
    const dns = `${n.host}.${config.tailnet_suffix}`;
    md += `| ${n.tier} | ${n.host} | \`${n.user}\` | ${n.port} | \`${dns}\` |\n`;
  }
  md += `\n## Connect\n\n\`\`\`bash\n`;
  md += `ssh -p ${config.ssh_port} ${config.ssh_user}@${config.primary_host}.${config.tailnet_suffix}\n`;
  if (config.backup_host) {
    md += `ssh -p ${config.ssh_port} ${config.ssh_user}@${config.backup_host}.${config.tailnet_suffix}\n`;
  }
  md += `\`\`\`\n`;
  return md;
}

function renderSshConfig(config) {
  const hosts = [config.primary_host, config.backup_host, ...config.extra_hosts.split(',').map((s) => s.trim()).filter(Boolean)].filter(Boolean);
  let snippet = `# Tailscale Devbox Fleet — append to ~/.ssh/config\n\n`;
  for (const host of hosts) {
    snippet += `Host ${host} ${host}.${config.tailnet_suffix}\n`;
    snippet += `    HostName ${host}.${config.tailnet_suffix}\n`;
    snippet += `    User ${config.ssh_user}\n`;
    snippet += `    Port ${config.ssh_port}\n`;
    snippet += `    IdentityFile ${config.identity_file}\n\n`;
  }
  return snippet;
}

function renderConfigYaml(config) {
  return `brain_name: "${config.brain_name}"
tailnet_suffix: "${config.tailnet_suffix}"
primary_host: "${config.primary_host}"
backup_host: "${config.backup_host}"
extra_hosts: "${config.extra_hosts}"
ssh_user: "${config.ssh_user}"
ssh_port: ${config.ssh_port}
identity_file: "${config.identity_file}"
acl_tag_owner: "${config.acl_tag_owner}"
`;
}

async function installGrokSkill(config) {
  const src = join(ROOT, 'skills', 'tailscale-devbox');
  const dst = join(homedir(), '.grok', 'skills', 'tailscale-devbox');
  if (!existsSync(join(src, 'SKILL.md'))) {
    console.warn('WARN: skill not found, skipping');
    return;
  }
  await mkdir(dst, { recursive: true });
  await cp(src, dst, { recursive: true, force: true });
  console.log(`  skill -> ${dst}`);
}

async function main() {
  console.log('==> Tailscale Devbox init\n');

  const defaults = await loadExample();
  let config;

  if (nonInteractive) {
    config = {
      brain_name: getArg('--brain', defaults.brain_name || 'my-brain'),
      tailnet_suffix: getArg('--tailnet', defaults.tailnet_suffix || 'example.ts.net'),
      primary_host: getArg('--primary', defaults.primary_host || 'devbox-1'),
      backup_host: getArg('--backup', defaults.backup_host || ''),
      extra_hosts: getArg('--extra', defaults.extra_hosts || ''),
      ssh_user: getArg('--user', defaults.ssh_user || 'deploy'),
      ssh_port: getArg('--port', defaults.ssh_port || '22222'),
      identity_file: getArg('--identity', defaults.identity_file || '~/.ssh/id_ed25519'),
      acl_tag_owner: getArg('--acl-owner', defaults.acl_tag_owner || 'you@github'),
    };
  } else {
    const rl = readline.createInterface({ input, output });
    config = {
      brain_name: await prompt(rl, 'Brain/orchestrator name', defaults.brain_name || 'my-brain'),
      tailnet_suffix: await prompt(rl, 'Tailnet DNS suffix (e.g. mytailnet.ts.net)', defaults.tailnet_suffix || 'example.ts.net'),
      primary_host: await prompt(rl, 'Primary Devbox hostname', defaults.primary_host || 'devbox-1'),
      backup_host: await prompt(rl, 'Backup Devbox hostname (optional)', defaults.backup_host || ''),
      extra_hosts: await prompt(rl, 'Extra hosts comma-separated (optional)', defaults.extra_hosts || ''),
      ssh_user: await prompt(rl, 'SSH user', defaults.ssh_user || 'deploy'),
      ssh_port: await prompt(rl, 'OpenSSH port on tailnet IP', defaults.ssh_port || '22222'),
      identity_file: await prompt(rl, 'SSH identity file', defaults.identity_file || '~/.ssh/id_ed25519'),
      acl_tag_owner: await prompt(rl, 'ACL tag:ssh-fleet owner (login@github)', defaults.acl_tag_owner || 'you@github'),
    };
    rl.close();
  }

  await mkdir(join(ROOT, 'fleet'), { recursive: true });
  await mkdir(join(ROOT, 'generated'), { recursive: true });

  await writeFile(join(ROOT, 'config.yaml'), renderConfigYaml(config));
  await writeFile(join(ROOT, 'fleet', 'registry.yaml'), renderRegistry(config));
  await writeFile(join(ROOT, 'generated', 'ssh-config.snippet'), renderSshConfig(config));

  console.log('\n==> Generated:');
  console.log('  config.yaml');
  console.log('  fleet/registry.yaml');
  console.log('  generated/ssh-config.snippet');

  if (installSkill || (!nonInteractive && args.includes('--install-skill'))) {
    console.log('\n==> Installing Grok skill...');
    await installGrokSkill(config);
  }

  console.log('\n==> Next steps:');
  console.log('  1. Paste templates/acl-ssh-fleet.jsonc into Tailscale admin ACL (set tag owner)');
  console.log('  2. On each Devbox host: bash scripts/bootstrap-ssh-node.sh --user', config.ssh_user, '--port', config.ssh_port);
  console.log('  3. Append generated/ssh-config.snippet to ~/.ssh/config');
  console.log('  4. Test: ssh -p', config.ssh_port, `${config.ssh_user}@${config.primary_host}.${config.tailnet_suffix}`);
  console.log('\nOptional: npm run init -- --install-skill');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});